### ISSUE TITLE
Migration to gradle-nexus-publish-plugin 

### ISSUE THREAD

**Issue by szpak** [rwinch/gradle-publish-ossrh-sample#4]
As a replacement for Nexus Staging and Nexus Publish there is a brand new (officially released during the weekend)  [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/), created by the same authors. You might give it a try and eventually also migrate your guide to it (and/or report any potential problem that you will spot :-) ).

I created an official migration guide, which could be helpful for you:
https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo

**Comment by rwinch** [comment]
Thanks! I had it in my README, but didn't realize it had been released. I'll take a look at updating to use it

**Comment by rwinch** [comment]
Thanks I have updated to the new plugin!
